// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe-0OJCtzNcygMdBl7HMaE1kJmIku5adQ',
    appId: '1:74183429248:web:867d95be923883a751ea65',
    messagingSenderId: '74183429248',
    projectId: 'ditonton-e41fa',
    authDomain: 'ditonton-e41fa.firebaseapp.com',
    storageBucket: 'ditonton-e41fa.appspot.com',
    measurementId: 'G-E0DNDL1YLK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLFZ3Gvp2rI5ggp8xuG0HYlUd5ya40uLc',
    appId: '1:74183429248:android:87f80e546417ae3d51ea65',
    messagingSenderId: '74183429248',
    projectId: 'ditonton-e41fa',
    storageBucket: 'ditonton-e41fa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbzhoSpQC8qMyH9EN1Ie4eXyPcUO-glBE',
    appId: '1:74183429248:ios:18e6b369c1e00a3051ea65',
    messagingSenderId: '74183429248',
    projectId: 'ditonton-e41fa',
    storageBucket: 'ditonton-e41fa.appspot.com',
    iosClientId: '74183429248-nf71kb6cn2f6qe5peq7ate8u0d71nd9o.apps.googleusercontent.com',
    iosBundleId: 'com.dicoding.ditonton',
  );
}
